<?php
/*
 * Copyright (C) PowerOn Sistemas
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/* @var $this PowerOn\View\View */
/* @var $exception \PowerOn\Exceptions\PowerOnException  */
$exception = $this->exception;
$reflection = new ReflectionClass($exception);
?>
<h1>Throw <em><?= $reflection->getShortName() ?></em> catched:</h1>
<h2><?= $exception->getMessage() ?></h2>
<p><strong>File</strong> : <?= $exception->getFile() ?> : <?= $exception->getLine() ?></p>
<p> <?= $exception->getHelp() ?> </p>
<h3> Trace </h3>
<?= $this->block->humaniceTrace($exception->getTrace()) ?>
<?php if ( $exception->getContext() ) : ?>
<h3> Context </h3>
<?php d($exception->getContext()) ?>
<?php endif ?>

<?php if ( $exception->getPrevious() ) : ?>
<h3> Previous Exception </h3>
<?php d($exception->getPrevious()) ?>
<?php endif ?>
