<?php
/*
 * Copyright (C) PowerOn Sistemas
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/* @var $this PowerOn\View\View */
/* @var $exception \PowerOn\Exceptions\PowerOnException */
$exception = $this->exception;
?>

<h1>La p&aacute;gina solicitada no existe</h1>
<p>La p&aacute;gina que esta intentando visitar ya no se encuentra en el servidor, si cree que es un error contacte al webmaster.</p>
